//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MeMes.Module.BusinessObjects.fts
{

    [DevExpress.Persistent.Base.DefaultClassOptions]
    public partial class Factory : XPObject
    {
        string fFactoryNo;
        [Size(10)]
        public string FactoryNo
        {
            get { return fFactoryNo; }
            set { SetPropertyValue<string>(nameof(FactoryNo), ref fFactoryNo, value); }
        }
        string fFactoryName;
        public string FactoryName
        {
            get { return fFactoryName; }
            set { SetPropertyValue<string>(nameof(FactoryName), ref fFactoryName, value); }
        }
        string fRemarkOfFactory;
        [Size(SizeAttribute.Unlimited)]
        public string RemarkOfFactory
        {
            get { return fRemarkOfFactory; }
            set { SetPropertyValue<string>(nameof(RemarkOfFactory), ref fRemarkOfFactory, value); }
        }
        [Association(@"WorkshopReferencesFactory")]
        public XPCollection<Workshop> Workshops { get { return GetCollection<Workshop>(nameof(Workshops)); } }
    }

}
