//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MeMes.Module.BusinessObjects.fts
{

    [DevExpress.Persistent.Base.DefaultClassOptions]
    public partial class ProductionLine : XPObject
    {
        string fProductionLineNo;
        [Size(10)]
        public string ProductionLineNo
        {
            get { return fProductionLineNo; }
            set { SetPropertyValue<string>(nameof(ProductionLineNo), ref fProductionLineNo, value); }
        }
        string fProductionLineName;
        public string ProductionLineName
        {
            get { return fProductionLineName; }
            set { SetPropertyValue<string>(nameof(ProductionLineName), ref fProductionLineName, value); }
        }
        string fRemarkOfProductionLine;
        [Size(SizeAttribute.Unlimited)]
        public string RemarkOfProductionLine
        {
            get { return fRemarkOfProductionLine; }
            set { SetPropertyValue<string>(nameof(RemarkOfProductionLine), ref fRemarkOfProductionLine, value); }
        }
        Workshop fWorkshop;
        [Association(@"ProductionLineReferencesWorkshop")]
        public Workshop Workshop
        {
            get { return fWorkshop; }
            set { SetPropertyValue<Workshop>(nameof(Workshop), ref fWorkshop, value); }
        }
        [Association(@"StationReferencesProductionLine")]
        public XPCollection<Station> Stations { get { return GetCollection<Station>(nameof(Stations)); } }
    }

}
