//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MeMes.Module.BusinessObjects.fts
{

    [DevExpress.Persistent.Base.DefaultClassOptions]
    public partial class Station : XPObject
    {
        string fStationNo;
        [Size(10)]
        public string StationNo
        {
            get { return fStationNo; }
            set { SetPropertyValue<string>(nameof(StationNo), ref fStationNo, value); }
        }
        string fStationName;
        public string StationName
        {
            get { return fStationName; }
            set { SetPropertyValue<string>(nameof(StationName), ref fStationName, value); }
        }
        string fRemarkOfStation;
        [Size(SizeAttribute.Unlimited)]
        public string RemarkOfStation
        {
            get { return fRemarkOfStation; }
            set { SetPropertyValue<string>(nameof(RemarkOfStation), ref fRemarkOfStation, value); }
        }
        ProductionLine fProductionLine;
        [Association(@"StationReferencesProductionLine")]
        public ProductionLine ProductionLine
        {
            get { return fProductionLine; }
            set { SetPropertyValue<ProductionLine>(nameof(ProductionLine), ref fProductionLine, value); }
        }

        public string ProdLineNo {
            get {
                if (ProductionLine == null) return null;
                return ProductionLine.ProductionLineNo;
            }
        }
    }
}
