//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;

namespace MeMes.Module.BusinessObjects.fts
{

    [DevExpress.Persistent.Base.DefaultClassOptions]
    public partial class Workshop : XPObject
    {
        string fWorkshopNo;
        [Size(10)]
        public string WorkshopNo
        {
            get { return fWorkshopNo; }
            set { SetPropertyValue<string>(nameof(WorkshopNo), ref fWorkshopNo, value); }
        }
        string fWorkshopName;
        public string WorkshopName
        {
            get { return fWorkshopName; }
            set { SetPropertyValue<string>(nameof(WorkshopName), ref fWorkshopName, value); }
        }
        string fRemarkOfWorkshop;
        [Size(SizeAttribute.Unlimited)]
        public string RemarkOfWorkshop
        {
            get { return fRemarkOfWorkshop; }
            set { SetPropertyValue<string>(nameof(RemarkOfWorkshop), ref fRemarkOfWorkshop, value); }
        }
        Factory fFatory;
        [Association(@"WorkshopReferencesFactory")]
        public Factory Fatory
        {
            get { return fFatory; }
            set { SetPropertyValue<Factory>(nameof(Fatory), ref fFatory, value); }
        }
        [Association(@"ProductionLineReferencesWorkshop")]
        public XPCollection<ProductionLine> ProductionLines { get { return GetCollection<ProductionLine>(nameof(ProductionLines)); } }

        // [PersistentAlias("FactoryNo")]
        [VisibleInDetailView(false),NonPersistent]
        public string FactoryNo
        {
            get
            {
                if (Fatory == null) return null;
                return Fatory.FactoryNo;
            }
        }
    }
}
